version: "3.8"
services:

  roostr:
    build: ./
    container_name: roostr
    volumes:
      - ./:/usr/src/app
      - roostr_node_modules:/usr/src/app/node_modules


volumes:
  roostr_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/node_modules
